### ISSUE TITLE
Add genesis functionality for `bellatrix`

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum-consensus#100]
`initialize_beacon_state_from_eth1` is missing from the `bellatrix` implementation, see here: https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/beacon-chain.md#testing

to add, we can copy from an earlier fork and just update the places where it has changed

will also want to re-run the spec gen so it is included in the `state_transition` code after it is implemented

**Comment by ralexstokes** [comment]
this likely also goes for `altair` as well

**Comment by dtbuchholz** [comment]
Should re-running the spec gen cause some import issues? Specifically, missing imports or unused ones (that cause warnings)? 

It impacts all of the files in `state_transition`, so before I go and clean things up, just wanna double check this is normal behavior (so that I don't do some unnecessary work).

**Comment by ralexstokes** [comment]
added in #138
